import { JourneyStory } from "@/components/sections/JourneyStory";
import { personalProjects } from "@/data/personalProjects";
import { professionalProjects } from "@/data/professionalProjects";
import { profile } from "@/data/profile";
import { research } from "@/data/research";
import { skillGroups } from "@/data/skills";

const nav=[["Home","#home"],["Journey","#journey"],["Work","#work"],["Projects","#projects"],["Research","#research"],["About","#about"]];
const principles=[
 ["01","Own Ambiguous Problems","Turn loosely defined business problems into measurable ML/AI problems, experiments, evaluation strategies, and deliverables."],
 ["02","Bridge Technical & Business Teams","Communicate model behavior, trade-offs, evaluation results, and implications in ways technical and business stakeholders can act on."],
 ["03","Build Toward Production","Think beyond prototypes by considering validation, reliability, usability, monitoring, and production readiness."],
];

function SectionHeading({index,kicker,title,copy}:{index:string;kicker:string;title:string;copy?:string}){return <div className="section-intro"><div><span className="section-index">{index} / {kicker}</span><h2>{title}</h2></div>{copy&&<p>{copy}</p>}</div>}
function Header(){return <header className="site-header"><a className="monogram" href="#home" aria-label="Jasleen Kaur Bhatia, home">{profile.shortName}<span>·</span></a><nav aria-label="Primary navigation">{nav.map(([label,href])=><a key={href} href={href}>{label}</a>)}</nav><div className="header-actions"><a className="icon-link" href="#contact" aria-label="Contact">@</a><a className="resume-small" href={profile.resumeUrl} download>Resume ↓</a></div></header>}

export default function Home(){return <main id="home"><Header/>
 <section className="hero section-shell" aria-labelledby="hero-title"><div className="eyebrow"><span className="signal"/> Data Scientist · ML, NLP & Generative AI</div><h1 id="hero-title">Jasleen Kaur<br/><span>Bhatia.</span></h1><div className="hero-grid"><div><p className="headline">{profile.headline}</p><p className="positioning">{profile.positioning}</p></div><div className="hero-aside"><p>{profile.supporting}</p><div className="hero-actions"><a className="button primary" href="#work">Explore my work ↘</a><a className="button text-button" href="#journey">Career journey ↓</a></div><div className="social-row"><a href="#contact">LinkedIn ↗</a><a href="#contact">GitHub ↗</a><a href="#contact">Email ↗</a></div></div></div><div className="data-ribbon" aria-hidden="true">{[["01","Experiment"],["02","Evaluate"],["03","Validate"],["04","Operationalize"]].map(([n,label])=><div key={n}><span>{n}</span><strong>{label}</strong></div>)}</div></section>

 <section id="journey" className="journey section-shell"><SectionHeading index="01" kicker="Career Journey" title="A career in chapters." copy="Six years building data foundations in India. A move to Chicago to formalize the craft. Then applied ML, predictive systems, NLP, and enterprise Generative AI."/><JourneyStory/></section>

 <section id="work" className="work section-shell"><SectionHeading index="02" kicker="Selected Professional Work" title="Systems, evaluated." copy="Selected public-safe case studies spanning enterprise GenAI, predictive modeling, NLP, and production readiness."/><div className="case-grid">{professionalProjects.map((project,i)=><a className={`case-card case-${i+1}`} href={`/work/${project.slug}`} key={project.slug}><div className="case-top"><span>0{i+1}</span><span>{project.category}</span></div><div><p className="org">{project.organization}{project.client&&<> · {project.client}</>}</p><h3>{project.title}</h3><p className="case-summary">{project.summary}</p></div><div className="metric-row">{project.metrics.slice(0,3).map(metric=><div key={metric.label}><strong>{metric.value}</strong><span>{metric.label}</span></div>)}</div><span className="case-link">View case study ↗</span></a>)}</div></section>

 <section id="projects" className="lab section-shell"><SectionHeading index="03" kicker="AI Lab" title="Building beyond the brief." copy="Independent systems for exploring research intelligence, personal data, and useful applied AI experiences."/><div className="project-grid">{personalProjects.map((project,i)=><article className="project-card" key={project.slug}><div className="project-head"><span className="project-no">0{i+1}</span><span className="status">{project.status}</span></div><h3>{project.name}</h3><p className="project-subtitle">{project.subtitle}</p><p>{project.description}</p>{project.slug==="litlens-ai"&&<div className="flow" aria-label="LitLens system flow">{["Research papers","Structured extraction","Evidence retrieval","RAG intelligence","Ask · Compare · Gaps"].map((s,j)=><span key={s}>{s}{j<4&&<b>→</b>}</span>)}</div>}<div className="tag-list">{project.technology.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>

 <section id="research" className="research section-shell"><SectionHeading index="04" kicker="Research & Exploration" title="Questions in motion." copy="Ongoing survey work on methods, datasets, and evaluation for understanding badminton through machine learning."/><div className="research-grid">{research.map((item,i)=><article key={item.title}><span className="research-index">R.0{i+1}</span><p className="status">{item.status} · {item.year}</p><h3>{item.title}</h3><div className="research-rule"><span/></div></article>)}</div></section>

 <section className="skills section-shell"><SectionHeading index="05" kicker="Technical Landscape" title="A connected practice." copy="Capabilities organized around how systems are explored, built, evaluated, and operated—not a keyword inventory."/><div className="skills-map">{skillGroups.map((group,i)=><article key={group.name}><span>0{i+1}</span><h3>{group.name}</h3><p>{group.items.join(" · ")}</p></article>)}</div></section>

 <section className="principles section-shell"><SectionHeading index="06" kicker="How I Work" title="Rigor, translated."/><div className="principle-grid">{principles.map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>

 <section id="about" className="about section-shell"><div className="about-layout"><div className="portrait-space">{profile.image?<img src={profile.image} alt="Jasleen Kaur Bhatia"/>:<div><span>PORTRAIT / OPTIONAL</span><b>JKB</b></div>}</div><div><span className="section-index">07 / ABOUT</span><h2>Ideas become useful<br/>through evaluation.</h2>{profile.about.map(p=><p key={p}>{p}</p>)}</div></div><div className="education-list"><span className="section-index">Education</span><div><strong>Master’s in Data Science</strong><span>Illinois Institute of Technology · Chicago, Illinois</span><em>2021–2023</em></div><div><strong>B.Tech in Computer Science</strong><span>IMS Engineering College · India</span><em>2010–2014</em></div></div></section>

 <footer id="contact"><div className="section-shell footer-grid"><div><span className="section-index">Let’s connect</span><h2>Continue the<br/>conversation.</h2></div><div className="contact-links"><a href="mailto:">Email <span>↗</span></a><a href="#">LinkedIn <span>↗</span></a><a href="#">GitHub <span>↗</span></a><a href={profile.resumeUrl} download>Resume <span>↓</span></a></div></div><div className="section-shell footer-base"><span>JASLEEN KAUR BHATIA</span><span>DATA · MODELS · SYSTEMS</span><span>© 2026</span></div></footer>
 </main>}
